# Generated by Django 4.1.1 on 2022-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rating', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
            ],
        ),
    ]
